### ISSUE TITLE
[Feature Request] Add to the Nextcloud appstore

### ISSUE THREAD

**Issue by sunjam** [kffl/nextcloud-webhooks#3]
Just want to send encouragement for adding your excellent webhooks app to the appstore.  [Here is documentation info](https://nextcloudappstore.readthedocs.io/en/latest/developer.html).  Thanks either way.

**Comment by kffl** [comment]
Thank you for encouragement! There are only some minor tweaks to be done prior to the appstore release. If everything goes well, I will publish the app this weekend.

**Comment by sunjam** [comment]
Cool, are you on the [forum](help.nextcloud.com)?  No doubt others there will be interested to learn about this.  :heart:

**Comment by kffl** [comment]
@sunjam The app is now available in the Nextcloud App Store. I have also signed up for the forum and posted a thread about this app: https://help.nextcloud.com/t/webhooks-app-for-custom-integrations/135903
